### ISSUE TITLE
bug report及功能建议

### ISSUE THREAD

**Issue by vefish** [Steven-AA/find-all-the-new-words#5]
bug：
this less radius minus continuous会被取成thi les radiu minu continuou，似乎某些以s结尾的单词处理时有问题？还没找到规律，比如同一个文件里yes会取成ye，而focus又不会取错
功能建议：
A. build时加一个选项4，因为有时候要处理的文本内的单词原本可能就有问题，如两个词连在一起被拆出来，建议把4设置成另存入一个单独的txt，后续单独处理
B. 添加中途退出继续上次处理的功能，比如要build的单词很多，允许处理部分后退出，下次继续，目前强制中断就做无用功了
C. 可否考虑加上一个按1后再按空格出简单释义的功能，有时一个单词觉得认识但是记错了，看了简单释义能确认下，如果不对可以用一个键比如3来修正到不认识里，回车继续，按3修正，如何
btw:
如果有一样遇到报错的朋友可以试着把pattern3.en改成pattern.en

**Comment by Steven-AA** [comment]
抱歉这么久才回复。我刚刚知道，即使是自己的仓库，如果不 watch 的话是无法收到邮件通知的。

我测试了一下，的确有这个问题，但是，这个是 pattern 的 bug， 我这边解决不了。除非换个包来实现词形还原。这个我再考虑一下。

A. 可以，下个版本加

B. 中途退出这个问题我会把它放到下一次更新里解决。方案大概是比如按 q 之后去保存 old.txt 和 new.txt， 然后把还在队列中的单词存成文件放到 todo 文件夹 （原 articles 文件夹），把原文章放到 finished 文件夹中。如果你别的想法的话，欢迎讨论。

C. 个人并不想加这个功能。因为，这个不是用来背单词的啊。这是服务于Anki来制卡的，从核心上来讲，其实是建立个人词库。”觉得认识“的单词不应该认为是你掌握的单词哦。

最后，你说”把 pattern3.en 改成 pattern.en“解决报错。请问是什么报错？你用的是 python2 吗？

谢谢
